"""Report Generator Service for Government Command Center.

Generates real physical files (PDF, Excel, CSV) on disk in backend/storage/reports/.
Sourcing:
- Risk Summary & Crop Health: Real aggregations from Hotspot model data.
- Yield Forecast & Intervention Log: Flagged as is_placeholder_content=True with clear disclaimers.
"""
from __future__ import annotations

import csv
import os
import re
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from fastapi import HTTPException, status
from fpdf import FPDF
from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from sqlalchemy.orm import Session

from app.models.risk_map import Hotspot
from app.models.intervention import Intervention

# Storage directory on local filesystem
STORAGE_DIR = Path(__file__).resolve().parent.parent.parent / "storage" / "reports"

VALID_REPORT_TYPES = [
    "Risk Summary",
    "Crop Health",
    "Yield Forecast",
    "Intervention Log",
]

VALID_FORMATS = ["PDF", "Excel", "CSV"]

FORMAT_MIME_TYPES = {
    "PDF": "application/pdf",
    "Excel": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "CSV": "text/csv",
}

FORMAT_EXTENSIONS = {
    "PDF": ".pdf",
    "Excel": ".xlsx",
    "CSV": ".csv",
}


def get_storage_dir() -> Path:
    """Ensure and return the reports storage directory."""
    STORAGE_DIR.mkdir(parents=True, exist_ok=True)
    return STORAGE_DIR


def validate_report_parameters(db: Session, report_type: str, district: str, format_type: str) -> list[str]:
    """Validate report type, format, and dynamic district presence in database."""
    if report_type not in VALID_REPORT_TYPES:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_CONTENT,
            detail=f"Invalid report type '{report_type}'. Valid types: {VALID_REPORT_TYPES}",
        )

    if format_type not in VALID_FORMATS:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_CONTENT,
            detail=f"Invalid format '{format_type}'. Valid formats: {VALID_FORMATS}",
        )

    # Dynamic district validation: query existing hotspot and intervention districts
    db_districts = [d[0] for d in db.query(Hotspot.district).distinct().all() if d[0]]
    intervention_districts = [d[0] for d in db.query(Intervention.district).distinct().all() if d[0]]
    valid_districts = sorted(set(db_districts + intervention_districts + ["All Districts"]))

    if district not in valid_districts:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_CONTENT,
            detail=f"Invalid district '{district}'. Valid districts: {valid_districts}",
        )

    return valid_districts


def _sanitize_string(val: str | None) -> str:
    """Sanitize text to standard ASCII/latin-1 for safe PDF rendering."""
    if not val:
        return ""
    # Replace Indian Rupee symbol with INR
    s = val.replace("₹", "INR ").replace("–", "-").replace("—", "-")
    s = s.replace("’", "'").replace("‘", "'").replace("“", '"').replace("”", '"')
    return s.encode("latin-1", "replace").decode("latin-1")


class ReportPDF(FPDF):
    """FPDF subclass with Telangana Agriculture Department branding."""

    def header(self):
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(22, 101, 52)  # Forest green
        self.cell(0, 8, "FasalSetu - Telangana Agriculture Department", border=False, align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_font("Helvetica", "I", 9)
        self.set_text_color(100, 116, 139)  # Slate gray
        self.cell(0, 5, "Official State Surveillance & Decision Support Analytics", border=False, align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(203, 213, 225)
        self.line(10, self.get_y() + 2, 200, self.get_y() + 2)
        self.ln(6)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(148, 163, 184)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by FasalSetu Government Command Center", align="C")


def generate_pdf_report(
    file_path: Path,
    title: str,
    metadata: dict[str, str],
    summary: str,
    findings: list[str],
    is_placeholder: bool,
    hotspots: list[Hotspot],
) -> int:
    """Generate a clean PDF report."""
    pdf = ReportPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # Report Title
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 10, _sanitize_string(title), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    # Metadata Grid
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(71, 85, 105)
    pdf.cell(40, 6, "Report Type:", border=False)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(55, 6, _sanitize_string(metadata.get("type", "")), border=False)

    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(40, 6, "District / Region:", border=False)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(55, 6, _sanitize_string(metadata.get("district", "")), border=False, new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(40, 6, "Time Window:", border=False)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(55, 6, _sanitize_string(metadata.get("date_range", "")), border=False)

    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(40, 6, "Generated Date:", border=False)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(55, 6, _sanitize_string(metadata.get("date", "")), border=False, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # Placeholder banner if applicable
    if is_placeholder:
        pdf.set_fill_color(254, 243, 199)  # Light Amber fill
        pdf.set_draw_color(245, 158, 11)  # Amber border
        pdf.set_text_color(180, 83, 9)
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(0, 6, " [NOTICE: DEMO PLACEHOLDER CONTENT]", fill=True, border=1, new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 8)
        disclaimer_text = (
            "Upstream telemetry aggregation models and government intervention tracking are currently under active "
            "development (Features 15d+). Metrics below represent structural mock schemas pending real field sensor links."
        )
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(pdf.epw, 4, _sanitize_string(disclaimer_text), fill=True, border=1)
        pdf.ln(4)

    # Executive Summary
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(22, 101, 52)
    pdf.cell(0, 8, "Executive Summary", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(51, 65, 85)
    pdf.set_x(pdf.l_margin)
    pdf.multi_cell(pdf.epw, 5, _sanitize_string(summary))
    pdf.ln(3)

    # Key Findings
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(22, 101, 52)
    pdf.cell(0, 8, "Strategic Observations & Key Findings", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(51, 65, 85)
    for item in findings:
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(pdf.epw, 5, _sanitize_string(f"-  {item}"))
    pdf.ln(4)

    # Hotspot Surveillance Table
    if hotspots:
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(15, 23, 42)
        pdf.cell(0, 7, f"Surveillance Hotspot Roster ({len(hotspots)} Active Threat Locations)", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_fill_color(241, 245, 249)
        pdf.set_text_color(30, 41, 59)

        # Columns: District(28), Crop(22), Threat(40), Sev(18), Ha(22), Impact(25), Farmers(25) = 180
        col_w = [28, 22, 42, 18, 22, 28, 20]
        headers = ["District", "Crop", "Primary Threat", "Severity", "Area (ha)", "Impact (INR Cr)", "Farmers"]
        for w, h in zip(col_w, headers):
            pdf.cell(w, 6, h, border=1, fill=True, align="C")
        pdf.ln()

        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(51, 65, 85)
        for h in hotspots:
            pdf.cell(col_w[0], 5, _sanitize_string(h.district)[:16], border=1)
            pdf.cell(col_w[1], 5, _sanitize_string(h.crop)[:14], border=1)
            pdf.cell(col_w[2], 5, _sanitize_string(h.issue_type)[:24], border=1)
            pdf.cell(col_w[3], 5, _sanitize_string(h.risk_level), border=1, align="C")
            pdf.cell(col_w[4], 5, f"{h.affected_area_ha:,.0f}", border=1, align="R")
            pdf.cell(col_w[5], 5, f"{h.economic_impact_cr:.2f}", border=1, align="R")
            pdf.cell(col_w[6], 5, f"{h.farmers_impacted:,}", border=1, align="R")
            pdf.ln()
    else:
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(100, 116, 139)
        pdf.cell(0, 6, "No direct physical hotspot records associated with this specific report scope.", new_x="LMARGIN", new_y="NEXT")

    pdf.output(str(file_path))
    return file_path.stat().st_size


def generate_excel_report(
    file_path: Path,
    title: str,
    metadata: dict[str, str],
    summary: str,
    findings: list[str],
    is_placeholder: bool,
    hotspots: list[Hotspot],
) -> int:
    """Generate a formatted Excel (.xlsx) report."""
    wb = Workbook()
    ws = wb.active
    ws.title = "Executive Summary"

    # Styles
    header_fill = PatternFill(start_color="166534", end_color="166534", fill_type="solid")
    header_font = Font(name="Calibri", size=14, bold=True, color="FFFFFF")
    section_font = Font(name="Calibri", size=11, bold=True, color="166534")
    body_font = Font(name="Calibri", size=10, color="1E293B")
    table_head_fill = PatternFill(start_color="F1F5F9", end_color="F1F5F9", fill_type="solid")
    table_head_font = Font(name="Calibri", size=10, bold=True, color="0F172A")
    thin_border = Border(
        left=Side(style="thin", color="CBD5E1"),
        right=Side(style="thin", color="CBD5E1"),
        top=Side(style="thin", color="CBD5E1"),
        bottom=Side(style="thin", color="CBD5E1"),
    )

    # Title Block
    ws.merge_cells("A1:G1")
    title_cell = ws["A1"]
    title_cell.value = title
    title_cell.fill = header_fill
    title_cell.font = header_font
    title_cell.alignment = Alignment(horizontal="center", vertical="center")
    ws.row_dimensions[1].height = 30

    # Metadata
    ws["A3"] = "Report Type:"
    ws["B3"] = metadata.get("type", "")
    ws["D3"] = "District:"
    ws["E3"] = metadata.get("district", "")
    ws["A4"] = "Date Range:"
    ws["B4"] = metadata.get("date_range", "")
    ws["D4"] = "Generated Date:"
    ws["E4"] = metadata.get("date", "")
    for row in [3, 4]:
        ws[f"A{row}"].font = Font(bold=True)
        ws[f"D{row}"].font = Font(bold=True)

    curr_row = 6
    if is_placeholder:
        ws.merge_cells(f"A{curr_row}:G{curr_row}")
        warn_cell = ws[f"A{curr_row}"]
        warn_cell.value = "NOTICE: DEMO PLACEHOLDER CONTENT - Telemetry aggregation and field interventions pending Feature 15d."
        warn_cell.fill = PatternFill(start_color="FEF3C7", end_color="FEF3C7", fill_type="solid")
        warn_cell.font = Font(name="Calibri", size=10, bold=True, color="B45309")
        curr_row += 2

    # Executive Summary
    ws[f"A{curr_row}"] = "Executive Summary"
    ws[f"A{curr_row}"].font = section_font
    curr_row += 1
    ws.merge_cells(f"A{curr_row}:G{curr_row}")
    ws[f"A{curr_row}"] = summary
    ws[f"A{curr_row}"].font = body_font
    curr_row += 2

    # Key Findings
    ws[f"A{curr_row}"] = "Key Findings"
    ws[f"A{curr_row}"].font = section_font
    curr_row += 1
    for item in findings:
        ws.merge_cells(f"A{curr_row}:G{curr_row}")
        ws[f"A{curr_row}"] = f"- {item}"
        ws[f"A{curr_row}"].font = body_font
        curr_row += 1
    curr_row += 2

    # Table of Hotspots if any
    if hotspots:
        ws[f"A{curr_row}"] = f"Surveillance Hotspot Records ({len(hotspots)} Total)"
        ws[f"A{curr_row}"].font = section_font
        curr_row += 1

        headers = ["District", "Crop", "Issue Type", "Risk Level", "Affected Area (ha)", "Economic Impact (Cr)", "Farmers Impacted"]
        for col_idx, h in enumerate(headers, 1):
            cell = ws.cell(row=curr_row, column=col_idx, value=h)
            cell.fill = table_head_fill
            cell.font = table_head_font
            cell.border = thin_border
            cell.alignment = Alignment(horizontal="center")
        curr_row += 1

        for h in hotspots:
            row_vals = [
                h.district,
                h.crop,
                h.issue_type,
                h.risk_level,
                h.affected_area_ha,
                h.economic_impact_cr,
                h.farmers_impacted,
            ]
            for col_idx, val in enumerate(row_vals, 1):
                cell = ws.cell(row=curr_row, column=col_idx, value=val)
                cell.font = body_font
                cell.border = thin_border
                if col_idx in [5, 6, 7]:
                    cell.alignment = Alignment(horizontal="right")
            curr_row += 1

    # Adjust column widths
    from openpyxl.utils import get_column_letter

    for col_idx, col in enumerate(ws.columns, 1):
        max_len = 0
        for cell in col:
            val_str = str(cell.value or "")
            # ignore long merged cell text for column width calculation
            if len(val_str) < 50:
                max_len = max(max_len, len(val_str))
        col_letter = get_column_letter(col_idx)
        ws.column_dimensions[col_letter].width = max(max_len + 3, 14)

    wb.save(str(file_path))
    return file_path.stat().st_size


def generate_csv_report(
    file_path: Path,
    title: str,
    metadata: dict[str, str],
    summary: str,
    findings: list[str],
    is_placeholder: bool,
    hotspots: list[Hotspot],
) -> int:
    """Generate a clean CSV report."""
    with open(file_path, mode="w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["# FasalSetu - Telangana Agriculture Department Surveillance Report"])
        writer.writerow([f"# Title: {title}"])
        writer.writerow([f"# Report Type: {metadata.get('type', '')}"])
        writer.writerow([f"# District: {metadata.get('district', '')}"])
        writer.writerow([f"# Date Range: {metadata.get('date_range', '')}"])
        writer.writerow([f"# Generated Date: {metadata.get('date', '')}"])
        if is_placeholder:
            writer.writerow(["# NOTICE: DEMO PLACEHOLDER CONTENT - Telemetry and field intervention pipelines pending Feature 15d."])
        writer.writerow([])
        writer.writerow(["# Executive Summary", summary])
        writer.writerow(["# Key Findings"])
        for item in findings:
            writer.writerow(["# -", item])
        writer.writerow([])

        # Table header & records
        writer.writerow([
            "Hotspot ID",
            "District",
            "Crop",
            "Issue Type",
            "Risk Level",
            "Affected Area (ha)",
            "Economic Impact (INR Cr)",
            "Farmers Impacted",
            "Interventions Count",
        ])
        for h in hotspots:
            interventions_count = len(h.interventions_list) if isinstance(h.interventions_list, list) else 0
            writer.writerow([
                h.id,
                h.district,
                h.crop,
                h.issue_type,
                h.risk_level,
                h.affected_area_ha,
                h.economic_impact_cr,
                h.farmers_impacted,
                interventions_count,
            ])

    return file_path.stat().st_size


def create_report_file(
    db: Session,
    report_type: str,
    district: str,
    date_range: str,
    format_type: str,
    custom_date: str | None = None,
) -> dict[str, Any]:
    """Compile content, validate parameters, and generate the physical report file on disk."""
    validate_report_parameters(db, report_type, district, format_type)
    storage_dir = get_storage_dir()

    # Content synthesis
    if report_type in ["Risk Summary", "Crop Health"]:
        query = db.query(Hotspot)
        if district != "All Districts":
            query = query.filter(Hotspot.district == district)
        hotspots = query.all()

        total_hotspots = len(hotspots)
        total_ha = sum(h.affected_area_ha for h in hotspots)
        total_impact = sum(h.economic_impact_cr for h in hotspots)
        total_farmers = sum(h.farmers_impacted for h in hotspots)

        is_placeholder = False
        summary = (
            f"Official agricultural surveillance summary for {district}. Identified {total_hotspots} active risk "
            f"zones directly impacting approximately {total_farmers:,} farming families across {total_ha:,.1f} hectares, "
            f"with an estimated aggregate economic risk of INR {total_impact:.2f} Cr."
        )
        findings = [
            f"Identified {total_hotspots} active surveillance zones across surveyed mandals requiring close monitoring.",
            f"Total estimated economic threat stands at INR {total_impact:.2f} Cr across {total_ha:,.1f} ha.",
            "High-priority containment protocols active; prompt chemical and biological supply distribution advised.",
        ]
    else:  # Yield Forecast, Intervention Log
        hotspots = []
        is_placeholder = True
        summary = (
            f"NOTICE: Placeholder report content for {district}. Statewide yield projections and localized government "
            f"intervention field logs are pending comprehensive telemetry model integration and Feature 15d deployment."
        )
        findings = [
            "Data displayed in this report represents structural placeholder schemas.",
            "Real-time yield loss projections and deployed government intervention logs will be fully connected in subsequent platform updates.",
        ]

    # Generate unique filename
    clean_type = re.sub(r"[^a-zA-Z0-9]", "_", report_type).lower()
    clean_dist = re.sub(r"[^a-zA-Z0-9]", "_", district).lower()
    uid = uuid.uuid4().hex[:10]
    ext = FORMAT_EXTENSIONS[format_type]
    file_name = f"report_{clean_type}_{clean_dist}_{uid}{ext}"
    file_path = storage_dir / file_name

    title = f"{report_type} - {district}"
    date_str = custom_date or datetime.now(timezone.utc).strftime("%Y-%m-%d")
    metadata = {
        "type": report_type,
        "district": district,
        "date_range": date_range,
        "date": date_str,
    }

    # Generate physical file
    if format_type == "PDF":
        file_size = generate_pdf_report(file_path, title, metadata, summary, findings, is_placeholder, hotspots)
    elif format_type == "Excel":
        file_size = generate_excel_report(file_path, title, metadata, summary, findings, is_placeholder, hotspots)
    else:  # CSV
        file_size = generate_csv_report(file_path, title, metadata, summary, findings, is_placeholder, hotspots)

    scope_str = f"{district} District • {date_range}" if district != "All Districts" else f"Statewide • {date_range}"

    return {
        "name": title,
        "type": report_type,
        "district": district,
        "date_generated": date_str,
        "date_range": date_range,
        "scope": scope_str,
        "format": format_type,
        "file_path": str(file_path),
        "file_name": file_name,
        "file_size_bytes": file_size,
        "is_placeholder_content": is_placeholder,
        "executive_summary": summary,
        "key_findings": findings,
    }

