"""
Pydantic Schemas for AI Negotiation Chat Assistant
==================================================
Defines request and response validation structures for the negotiation advisory endpoint.
"""

from pydantic import BaseModel, Field


class NegotiationChatRequest(BaseModel):
    message: str = Field(
        ...,
        min_length=2,
        max_length=1000,
        description="Question or advisory inquiry about the active negotiation thread"
    )


class NegotiationChatResponse(BaseModel):
    reply: str = Field(
        ...,
        description="Advisory guidance generated by the AI negotiation assistant"
    )
    market_context_used: bool = Field(
        ...,
        description="Whether real recorded mandi price benchmarks were available and injected into context"
    )
